--!nonstrict
--[[
	modules/init.lua — module index.
	AUTO-GENERATED by scripts/bundle.py from the files discovered under src/modules/.
	Adding src/modules/<name>.lua makes it available as require("modules.<name>").
]]
local modules = {};

modules["modules.example"] = require("modules.modules.example");

return modules;
