--!nonstrict
--[[
	modules/init.lua — module index.
	AUTO-GENERATED by scripts/bundle.py from the files discovered under src/modules/.
	Adding src/modules/<name>.lua makes it available as require("modules.<name>").
]]
local modules = {};

modules["modules.aimbot"] = require("modules.modules.aimbot");
modules["modules.animations"] = require("modules.modules.animations");
modules["modules.assets"] = require("modules.modules.assets");
modules["modules.aura"] = require("modules.modules.aura");
modules["modules.backtrack"] = require("modules.modules.backtrack");
modules["modules.backtrack_chams"] = require("modules.modules.backtrack_chams");
modules["modules.bot_esp"] = require("modules.modules.bot_esp");
modules["modules.bullet_tracers"] = require("modules.modules.bullet_tracers");
modules["modules.camera"] = require("modules.modules.camera");
modules["modules.character"] = require("modules.modules.character");
modules["modules.chinahat"] = require("modules.modules.chinahat");
modules["modules.circles"] = require("modules.modules.circles");
modules["modules.combat"] = require("modules.modules.combat");
modules["modules.config"] = require("modules.modules.config");
modules["modules.constellations"] = require("modules.modules.constellations");
modules["modules.cosmetics"] = require("modules.modules.cosmetics");
modules["modules.crosshair"] = require("modules.modules.crosshair");
modules["modules.example"] = require("modules.modules.example");
modules["modules.fun_hud"] = require("modules.modules.fun_hud");
modules["modules.gamefx"] = require("modules.modules.gamefx");
modules["modules.glyphs"] = require("modules.modules.glyphs");
modules["modules.gunchams"] = require("modules.modules.gunchams");
modules["modules.killfx"] = require("modules.modules.killfx");
modules["modules.lighting"] = require("modules.modules.lighting");
modules["modules.links"] = require("modules.modules.links");
modules["modules.loading"] = require("modules.modules.loading");
modules["modules.menu"] = require("modules.modules.menu");
modules["modules.misc"] = require("modules.modules.misc");
modules["modules.models"] = require("modules.modules.models");
modules["modules.motiongraph"] = require("modules.modules.motiongraph");
modules["modules.music"] = require("modules.modules.music");
modules["modules.preview"] = require("modules.modules.preview");
modules["modules.server"] = require("modules.modules.server");
modules["modules.shaders"] = require("modules.modules.shaders");
modules["modules.social"] = require("modules.modules.social");
modules["modules.starfall"] = require("modules.modules.starfall");
modules["modules.trade"] = require("modules.modules.trade");
modules["modules.trail"] = require("modules.modules.trail");
modules["modules.weather"] = require("modules.modules.weather");
modules["modules.world_fx_math"] = require("modules.modules.world_fx_math");

return modules;
