#!/usr/bin/env python3
"""
bundle.py — build dist/main.lua, the self-contained executor script.

Bundle layout (single Luau chunk):

    --!nonstrict
    --[[ generated header ]]
    local __SOURCES = { ... }            -- source-string modules (raw payload text)
    local __FACTORIES = {}               -- code modules (executed once, cached)
    local function require(name) ... end -- tiny runtime require shim
    __FACTORIES["modules.X"] = function() ... end
    <src/init.lua verbatim — the original top-level driver>

Module kinds:
    * source-string modules ("neverlose", "visualsui", "assets",
      "neverlose.skins") — require() returns the EXACT string the original
      monolithic script had in its long-bracket literals. They are later
      loadstring()'d / JSONDecode()'d by the driver, preserving behavior.
    * code modules ("modules.*") — discovered under src/modules/, wrapped in
      factories, executed once, result cached (nil-safe).

The bundler guarantees:
    * every require("...") literal in the output resolves
    * no duplicate module names
    * a safe long-bracket level is chosen per embedded payload
    * src/modules/init.lua stays in sync with discovery
"""

from __future__ import annotations

import datetime
import hashlib
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

SOURCE_MODULES: dict[str, Path] = {
    "neverlose": PROJECT_ROOT / "src" / "neverlose" / "init.lua",
    "visualsui": PROJECT_ROOT / "src" / "visualsui" / "init.luau",
    "neverlose.skins": PROJECT_ROOT / "src" / "neverlose" / "skins.luau",
}
ASSETS_MODULE = ("assets", PROJECT_ROOT / "assets" / "boot_data.json")
ENTRY = PROJECT_ROOT / "src" / "init.lua"
MODULES_DIR = PROJECT_ROOT / "src" / "modules"

MODULES_INIT_HEADER = """\
--!nonstrict
--[[
\tmodules/init.lua — module index.
\tAUTO-GENERATED by scripts/bundle.py from the files discovered under src/modules/.
\tAdding src/modules/<name>.lua makes it available as require("modules.<name>").
]]
local modules = {{}};

{ENTRIES}\
return modules;
"""


class BundleError(Exception):
    pass


def strip_lua_comments(text: str) -> str:
    """Remove Lua comments while preserving string literals (long strings kept)."""
    out: list[str] = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c in ('"', "'"):
            quote = c
            out.append(c)
            i += 1
            while i < n:
                ch = text[i]
                out.append(ch)
                if ch == "\\" and i + 1 < n:
                    out.append(text[i + 1])
                    i += 2
                    continue
                i += 1
                if ch == quote:
                    break
            continue
        m = re.compile(r"\[(=*)\[").match(text, i)
        if c == "[" and m:
            close = "]" + "=" * len(m.group(1)) + "]"
            end = text.find(close, m.end())
            end = n if end < 0 else end + len(close)
            out.append(text[i:end])
            i = end
            continue
        m = re.compile(r"--\[(=*)\[").match(text, i)
        if c == "-" and m:
            close = "]" + "=" * len(m.group(1)) + "]"
            end = text.find(close, m.end())
            i = n if end < 0 else end + len(close)
            continue
        if c == "-" and i + 1 < n and text[i + 1] == "-":
            end = text.find("\n", i)
            i = n if end < 0 else end
            continue
        out.append(c)
        i += 1
    return "".join(out)


def read_exact(path: Path) -> str:
    """Read file bytes WITHOUT newline translation (keeps CRLF byte-exact)."""
    return path.read_bytes().decode("utf-8")


def write_exact(path: Path, text: str) -> None:
    path.write_bytes(text.encode("utf-8"))


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def choose_long_bracket(content: str) -> tuple[str, str]:
    """Pick the lowest long-bracket level that cannot collide with content."""
    level = 0
    while True:
        open_b = "[" + "=" * level + "["
        close_b = "]" + "=" * level + "]"
        if open_b in content or close_b in content:
            level += 1
            continue
        # seam safety: content must not end with a prefix of close_b, or the
        # concatenation content..close_b would close the string early.
        if any(content.endswith(close_b[:k]) for k in range(1, len(close_b))):
            level += 1
            continue
        if content.startswith("\n") or content.startswith("\r"):
            raise BundleError("embedded content must not start with a line break (Lua skips it)")
        return open_b, close_b


def embed(name: str, content: str) -> str:
    open_b, close_b = choose_long_bracket(content)
    return f'__SOURCES["{name}"] = {open_b}{content}{close_b};\n'


def discover_code_modules() -> dict[str, Path]:
    """Recursively discover modules under src/modules/ (dotted module ids)."""
    found: dict[str, Path] = {}
    for pattern in ("*.lua", "*.luau"):
        for path in MODULES_DIR.rglob(pattern):
            rel = path.relative_to(MODULES_DIR)
            parts = list(rel.with_suffix("").parts)
            if parts == ["init"]:
                continue  # the generated index
            module_id = "modules." + ".".join(parts)
            if module_id in found:
                raise BundleError(f"duplicate module id: {module_id} ({path})")
            found[module_id] = path
    return dict(sorted(found.items()))


def generate_modules_init(module_ids: list[str]) -> str:
    entries = "".join(f'modules["{mid}"] = require("modules.{mid}");\n' for mid in module_ids)
    if module_ids:
        entries += "\n"
    return MODULES_INIT_HEADER.format(ENTRIES=entries)


def main() -> int:
    for name, path in SOURCE_MODULES.items():
        if not path.exists():
            raise BundleError(f"missing source module file: {path} (run `make extract` first)")
    assets_path = ASSETS_MODULE[1]
    if not assets_path.exists():
        raise BundleError(f"missing asset payload: {assets_path} (run `make extract` first)")
    if not ENTRY.exists():
        raise BundleError(f"missing entrypoint: {ENTRY} (run `make extract` first)")

    # ---- gather contents ----------------------------------------------------
    sources: dict[str, str] = {}
    report_sources: dict[str, dict] = {}
    for name, path in SOURCE_MODULES.items():
        text = read_exact(path)
        sources[name] = text
        report_sources[name] = {"file": str(path.relative_to(PROJECT_ROOT)),
                                "sha256": sha256_text(text), "chars": len(text)}
    assets_text = read_exact(assets_path)
    sources[ASSETS_MODULE[0]] = assets_text
    report_sources[ASSETS_MODULE[0]] = {"file": str(assets_path.relative_to(PROJECT_ROOT)),
                                        "sha256": sha256_text(assets_text), "chars": len(assets_text)}

    code_modules = discover_code_modules()
    module_contents: dict[str, str] = {}
    report_modules: dict[str, dict] = {}
    for mid, path in code_modules.items():
        text = read_exact(path)
        module_contents[mid] = text
        report_modules[mid] = {"file": str(path.relative_to(PROJECT_ROOT)),
                               "sha256": sha256_text(text), "chars": len(text)}

    # duplicate check across every registry key
    all_ids = list(sources.keys()) + list(module_contents.keys()) + ["modules"]
    if len(all_ids) != len(set(all_ids)):
        dupes = {x for x in all_ids if all_ids.count(x) > 1}
        raise BundleError(f"duplicate module names: {sorted(dupes)}")

    # keep src/modules/init.lua in sync with discovery
    modules_init_text = generate_modules_init(list(code_modules.keys()))
    modules_init_path = MODULES_DIR / "init.lua"
    if not modules_init_path.exists() or read_exact(modules_init_path) != modules_init_text:
        write_exact(modules_init_path, modules_init_text)
        print(f"[bundle] regenerated {modules_init_path.relative_to(PROJECT_ROOT)}")

    entry_text = read_exact(ENTRY)
    if not entry_text.lstrip().startswith("--!nonstrict"):
        raise BundleError("src/init.lua must start with --!nonstrict")

    # ---- emit ----------------------------------------------------------------
    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    out: list[str] = []
    out.append("--!nonstrict")
    out.append("--[[")
    out.append("\tdist/main.lua — SELF-CONTAINED BUNDLE (generated by scripts/bundle.py)")
    out.append(f"\tgenerated: {now}")
    out.append("\tsource:    input/message(47).txt (monolithic VisualsUI executor script)")
    out.append("")
    out.append("\tEmbedded source-string modules (byte-exact payloads, loadstring'd by the driver):")
    for name, meta in report_sources.items():
        out.append(f"\t  {name:<16} {meta['chars']:>9,} chars  sha256 {meta['sha256'][:16]}...")
    out.append("\tCode modules (require factories):")
    out.append(f"\t  modules.init     auto-generated index of {len(code_modules)} discovered module(s)")
    for mid in code_modules:
        out.append(f"\t  {mid:<16} {report_modules[mid]['chars']:>9,} chars")
    out.append("")
    out.append("\tEverything after the entrypoint marker is src/init.lua verbatim.")
    out.append("]]")
    out.append("")
    out.append("-- ===== SOURCE-STRING MODULES (require returns the raw string) =====")
    out.append("local __SOURCES = {};")
    for name in ("neverlose", "visualsui", "assets", "neverlose.skins"):
        out.append(embed(name, sources[name]).rstrip("\n"))
    out.append("")
    out.append("-- ===== RUNTIME REQUIRE SHIM =====")
    out.append("local __FACTORIES = {};")
    out.append("local __CACHE = {};")
    out.append("local __NIL = {};")
    out.append("")
    out.append("local function require(moduleName)")
    out.append("\tif type(moduleName) ~= \"string\" then")
    out.append("\t\terror(\"require: module name must be a string, got \" .. type(moduleName), 2);")
    out.append("\tend;")
    out.append("\tlocal cached = __CACHE[moduleName];")
    out.append("\tif cached == __NIL then return nil; end;")
    out.append("\tif cached ~= nil then return cached; end;")
    out.append("\tlocal source = __SOURCES[moduleName];")
    out.append("\tif source ~= nil then")
    out.append("\t\t__CACHE[moduleName] = source;")
    out.append("\t\treturn source;")
    out.append("\tend;")
    out.append("\tlocal factory = __FACTORIES[moduleName];")
    out.append("\tif not factory then")
    out.append("\t\terror(\"require: module '\" .. moduleName .. \"' is not registered in this bundle\", 2);")
    out.append("\tend;")
    out.append("\tlocal result = factory();")
    out.append("\t__CACHE[moduleName] = (result == nil) and __NIL or result;")
    out.append("\treturn result;")
    out.append("end;")
    out.append("")
    out.append("-- ===== CODE MODULES =====")
    out.append("__FACTORIES[\"modules\"] = function()")
    out.append("\tlocal modules = {};")
    for mid in code_modules:
        out.append(f"\tmodules[\"{mid}\"] = require(\"{mid}\");")
    out.append("\treturn modules;")
    out.append("end;")
    for mid, content in module_contents.items():
        out.append(f"__FACTORIES[\"{mid}\"] = function()")
        out.append(f"-- <{report_modules[mid]['file']}>")
        out.append(content.rstrip("\n"))
        out.append("end;")
    out.append("")
    out.append("-- ===== ENTRYPOINT (src/init.lua, verbatim) =====")
    out.append(entry_text.rstrip("\n"))
    out.append("")

    bundle_text = "\n".join(out)

    # ---- self-checks ----------------------------------------------------------
    required = set(sources.keys()) | set(module_contents.keys()) | {"modules"}
    referenced = set(re.findall(r'require\s*\(\s*"([^"]+)"\s*\)', strip_lua_comments(bundle_text)))
    unresolved = sorted(referenced - required)
    if unresolved:
        raise BundleError(f"unresolved require() literals in bundle: {unresolved}")

    dist_dir = PROJECT_ROOT / "dist"
    dist_dir.mkdir(parents=True, exist_ok=True)
    write_exact(dist_dir / "main.lua", bundle_text)

    report = {
        "generated_utc": now,
        "entry": "src/init.lua",
        "source_modules": report_sources,
        "code_modules": {"modules": {"generated": True, "file": "src/modules/init.lua"}, **report_modules},
        "dist": {
            "file": "dist/main.lua",
            "sha256": sha256_text(bundle_text),
            "bytes": len(bundle_text.encode("utf-8")),
        },
    }
    write_exact(dist_dir / "bundle_report.json", json.dumps(report, indent=2, ensure_ascii=False) + "\n")

    print(f"[bundle] dist/main.lua: {len(bundle_text.encode('utf-8')):,} bytes, "
          f"{len(sources)} source modules, {len(code_modules) + 1} code modules")
    print(f"[bundle] sha256 {report['dist']['sha256'][:16]}...")
    print("[bundle] self-check: all require() literals resolve, no duplicate module ids")
    print("[bundle] DONE")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BundleError as exc:
        print(f"BUNDLE FAILED: {exc}", file=sys.stderr)
        sys.exit(2)
