#!/usr/bin/env python3
"""
extract.py — split the monolithic input/message(47).txt into the modular project.

The input file layout (verified before every write):

    local SOURCE, LIBRARY_SOURCE = [===[ <SOURCE> ]===], [===[ <LIBRARY_SOURCE> ]===];
    local BOOT_DATA = [===[ <BOOT_DATA JSON> ]===];

    local SKIN_SOURCE = [===[ <SKIN_SOURCE> ]===];
    <driver body — top-level bootstrap code, ends with `return Visuals;`>

Extraction map:
    SOURCE          -> src/neverlose/init.lua      (raw chunk, byte-exact)
    LIBRARY_SOURCE  -> src/visualsui/init.luau     (raw chunk, byte-exact)
    BOOT_DATA       -> assets/boot_data.json       (exact JSON string)
                      + assets/manifest.json
                      + assets/text/*               (flattened: '/' -> '_')
                      + assets/binary/*             (base64-decoded bytes)
    SKIN_SOURCE     -> src/neverlose/skins.luau    (raw chunk, byte-exact)
    driver body     -> embedded verbatim as the tail of src/init.lua

Long-bracket semantics (Lua/Luau): if the first character after the opening
bracket is a line break, exactly that one break is skipped. This script
replicates that rule so extracted payloads are the *exact string values* the
original chunk produced at runtime.

A SHA256 manifest of every extracted payload is written to
scripts/extract_manifest.json for downstream verification.
"""

from __future__ import annotations

import base64
import datetime
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
INPUT_FILE = PROJECT_ROOT / "input" / "message(47).txt"

MARKER = "-- [ EXTRACTED DRIVER BODY — everything below is byte-exact from input/message(47).txt ]"


class ExtractionError(Exception):
    pass


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def parse_long_bracket(text: str, pos: int, where: str) -> tuple[str, int]:
    """Parse a Lua long-bracket string starting at `pos`; return (value, end_pos).

    `end_pos` points just past the closing bracket. Applies Lua's
    skip-one-leading-newline rule so the returned value matches runtime semantics.
    """
    m = re.compile(r"\[(=*)\[").match(text, pos)
    if not m:
        raise ExtractionError(f"{where}: expected long-bracket opening at offset {pos}, found {text[pos:pos+12]!r}")
    level = len(m.group(1))
    close = "]" + "=" * level + "]"
    close_at = text.find(close, m.end())
    if close_at < 0:
        raise ExtractionError(
            f"INPUT_TRUNCATED: missing closing delimiter for {where} "
            f"(expected {close!r} after offset {m.end()})"
        )
    body = text[m.end():close_at]
    # Lua: skip exactly one leading line break (\r\n, \n or \r)
    if body.startswith("\r\n"):
        body = body[2:]
    elif body.startswith("\n") or body.startswith("\r"):
        body = body[1:]
    return body, close_at + len(close)


def expect(text: str, pos: int, literal: str, where: str) -> int:
    if not text.startswith(literal, pos):
        found = text[pos:pos + len(literal) + 24]
        raise ExtractionError(f"{where}: expected {literal!r} at offset {pos}, found {found!r}")
    return pos + len(literal)


def parse_input(text: str) -> dict:
    """Parse the four long-bracket payloads + trailing driver body."""
    pos = expect(text, 0, "local SOURCE, LIBRARY_SOURCE = ", "header")
    source, pos = parse_long_bracket(text, pos, "SOURCE")
    pos = expect(text, pos, ", ", "LIBRARY_SOURCE separator")
    library, pos = parse_long_bracket(text, pos, "LIBRARY_SOURCE")
    pos = expect(text, pos, ";", "LIBRARY_SOURCE close")
    pos = expect(text, pos, "\r\nlocal BOOT_DATA = ", "BOOT_DATA open")
    boot_data, pos = parse_long_bracket(text, pos, "BOOT_DATA")
    pos = expect(text, pos, ";", "BOOT_DATA close")
    pos = expect(text, pos, "\r\n\r\nlocal SKIN_SOURCE = ", "SKIN_SOURCE open")
    skin, pos = parse_long_bracket(text, pos, "SKIN_SOURCE")
    pos = expect(text, pos, ";", "SKIN_SOURCE close")
    driver = text[pos:]
    if driver.startswith("\r\n"):
        driver = driver[2:]
    elif driver.startswith("\n"):
        driver = driver[1:]
    elif driver.startswith("\r"):
        driver = driver[1:]
    if not driver:
        raise ExtractionError("driver body is empty — input truncated?")
    if not driver.rstrip().endswith("return Visuals;"):
        raise ExtractionError(
            "INPUT_TRUNCATED: driver body does not end with 'return Visuals;' "
            f"(ends with {driver.rstrip()[-60:]!r})"
        )
    return {"SOURCE": source, "LIBRARY_SOURCE": library, "BOOT_DATA": boot_data,
            "SKIN_SOURCE": skin, "DRIVER": driver}


PROLOGUE = """\
--!nonstrict
--[[
\tVisualsUI bootstrap — modular build.
\tGenerated by scripts/extract.py from input/message(47).txt.

\tThis file is the only entrypoint. The four payload strings of the original
\tmonolithic script are provided by the module system:

\t\trequire("neverlose")         -> SOURCE          (Luau chunk as a string)
\t\trequire("visualsui")         -> LIBRARY_SOURCE  (Luau chunk as a string)
\t\trequire("assets")            -> BOOT_DATA       (JSON string)
\t\trequire("neverlose.skins")   -> SKIN_SOURCE     (Luau chunk as a string)
\t\trequire("modules")           -> table of discovered code modules

\tThe chunk body below the marker is the original top-level driver, embedded
\tbyte-exactly, so execution order and behavior are identical to the original.
]]
local SOURCE = require("neverlose");
local LIBRARY_SOURCE = require("visualsui");
local BOOT_DATA = require("assets");
local SKIN_SOURCE = require("neverlose.skins");
local MODULES = require("modules");

{MARKER}
"""

MODULES_INIT_HEADER = """\
--!nonstrict
--[[
\tmodules/init.lua — module index.
\tAUTO-GENERATED by scripts/bundle.py from the files discovered under src/modules/.
\tAdding src/modules/<name>.lua makes it available as require("modules.<name>").
]]
local modules = {{}};

{ENTRIES}\
return modules;
"""

ASSETS_INIT = """\
--!nonstrict
--[[
	assets/init.lua — BOOT_DATA provider (dev mode).

	The original monolithic script inlined BOOT_DATA as a JSON string inside a
	long-bracket literal. The bootstrap driver expects require("assets") to
	return that exact JSON string (the driver runs
	HttpService:JSONDecode(BOOT_DATA) and then drops the reference).

	In the bundled dist/main.lua, scripts/bundle.py embeds the JSON from
	assets/boot_data.json verbatim as a source-string module, so this loader is
	bypassed and runtime behavior is byte-identical to the original.

	For un-bundled (dev) execution this loader reads assets/boot_data.json
	relative to getgenv().VISUALS_ROOT (the folder containing assets/).
	If VISUALS_ROOT is unset, the executor workspace root is assumed.
]]
local REL = "assets/boot_data.json"
local ROOT = (getgenv and getgenv().VISUALS_ROOT) or ""

local function fail(message)
	error("[assets] " .. message, 0)
end

if type(readfile) ~= "function" then
	fail("readfile is unavailable; run the bundled dist/main.lua or provide an executor environment.")
end

local path = ROOT .. REL

if type(isfile) == "function" and not isfile(path) then
	fail(
		"missing "
			.. path
			.. " — set getgenv().VISUALS_ROOT to the folder containing assets/, or use the bundled dist/main.lua."
	)
end

local ok, body = pcall(readfile, path)
if not ok or type(body) ~= "string" or body:sub(1, 1) ~= "{" then
	fail("could not read BOOT_DATA JSON from " .. path)
end

return body
"""

EXAMPLE_MODULE = """\
--!nonstrict
--[[
	modules/example.lua — template for new modules.

	Pattern:
	  1. drop a .lua/.luau file into src/modules/
	  2. run `make bundle` — the bundler auto-discovers it and regenerates
	     the modules index (src/modules/init.lua)
	  3. require it as require("modules.<name>") from anywhere in the project

	Module factories run once and are cached; return your public table.
]]
local Example = {}

Example.name = "example"

function Example.hello()
	return "hello from " .. Example.name
end

return Example
"""


def write_bytes(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def write_text(path: Path, text: str) -> None:
    write_bytes(path, text.encode("utf-8"))


def main() -> int:
    if not INPUT_FILE.exists():
        print(f"ERROR: input file not found: {INPUT_FILE}", file=sys.stderr)
        return 1

    raw = INPUT_FILE.read_bytes()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ExtractionError(f"input is not valid UTF-8: {exc}") from exc

    print(f"[extract] input: {INPUT_FILE.name} ({len(raw):,} bytes, sha256 {sha256(raw)[:16]}...)")

    payloads = parse_input(text)
    print("[extract] parsed payloads: SOURCE, LIBRARY_SOURCE, BOOT_DATA, SKIN_SOURCE + driver body")

    # ---- BOOT_DATA validation & split -------------------------------------
    try:
        boot = json.loads(payloads["BOOT_DATA"])
    except json.JSONDecodeError as exc:
        raise ExtractionError(f"BOOT_DATA is not valid JSON: {exc}") from exc

    if set(boot.keys()) != {"manifest", "text", "binary"}:
        raise ExtractionError(f"BOOT_DATA top-level keys unexpected: {sorted(boot.keys())}")

    manifest = boot["manifest"]
    files = manifest["files"]
    if manifest["count"] != len(files):
        raise ExtractionError(f"manifest.count={manifest['count']} != files={len(files)}")
    if manifest["total"] != sum(files.values()):
        raise ExtractionError("manifest.total != sum of file sizes")

    binary_assets: dict[str, str] = {}
    for rel, b64 in boot["binary"].items():
        try:
            decoded = base64.b64decode(b64, validate=True)
        except Exception as exc:  # noqa: BLE001
            raise ExtractionError(f"binary asset {rel}: invalid base64: {exc}") from exc
        declared = files.get(rel)
        if declared is None:
            raise ExtractionError(f"binary asset {rel} not present in manifest.files")
        if len(decoded) != declared:
            raise ExtractionError(f"binary asset {rel}: decoded {len(decoded)} != declared {declared}")
        if base64.b64encode(decoded).decode("ascii") != b64:
            raise ExtractionError(f"binary asset {rel}: base64 re-encode mismatch (non-standard encoding)")
        binary_assets[rel] = b64

    text_assets: dict[str, str] = {}
    for rel, body in boot["text"].items():
        declared = files.get(rel)
        if declared is None:
            raise ExtractionError(f"text asset {rel} not present in manifest.files")
        if not isinstance(body, str):
            raise ExtractionError(f"text asset {rel} is not a string")
        text_assets[rel] = body

    # skybox cross-check: skyboxes/<name>_<face>.jpg <-> manifest.skyboxes
    sky_pattern = re.compile(r"^skyboxes/(.+)_([a-z]{2})\.jpg$")
    sky_files: dict[str, set[str]] = {}
    for rel in files:
        m = sky_pattern.match(rel)
        if m:
            sky_files.setdefault(m.group(1), set()).add(m.group(2))
    skyboxes = manifest["skyboxes"]
    if set(skyboxes.keys()) != set(sky_files.keys()):
        raise ExtractionError("manifest.skyboxes names do not match skyboxes/* manifest.files entries")
    for name, faces in skyboxes.items():
        if set(faces) != sky_files[name]:
            raise ExtractionError(f"skybox {name}: faces {sorted(faces)} != files {sorted(sky_files[name])}")

    print(f"[extract] BOOT_DATA OK: {len(files)} manifest files, {len(text_assets)} text, {len(binary_assets)} binary, "
          f"{len(skyboxes)} skyboxes")

    # ---- write payload files ----------------------------------------------
    write_text(PROJECT_ROOT / "src" / "neverlose" / "init.lua", payloads["SOURCE"])
    write_text(PROJECT_ROOT / "src" / "visualsui" / "init.luau", payloads["LIBRARY_SOURCE"])
    write_text(PROJECT_ROOT / "src" / "neverlose" / "skins.luau", payloads["SKIN_SOURCE"])
    write_text(PROJECT_ROOT / "assets" / "boot_data.json", payloads["BOOT_DATA"])

    prologue = PROLOGUE.replace("{MARKER}", MARKER)
    write_text(PROJECT_ROOT / "src" / "init.lua", prologue + payloads["DRIVER"])

    # ---- write asset files --------------------------------------------------
    manifest_json = json.dumps(manifest, separators=(",", ":"), ensure_ascii=False)
    write_text(PROJECT_ROOT / "assets" / "manifest.json", manifest_json)

    text_meta = []
    for rel in sorted(text_assets):
        flat = rel.replace("/", "_")
        write_text(PROJECT_ROOT / "assets" / "text" / flat, text_assets[rel])
        text_meta.append({
            "path": rel,
            "file": f"assets/text/{flat}",
            "sha256": sha256(text_assets[rel].encode("utf-8")),
            "declared_size": files[rel],
            "embedded_len": len(text_assets[rel]),
        })

    binary_meta = []
    for rel in sorted(binary_assets):
        rel_path = rel.replace("\\", "/")
        if rel_path.startswith("/") or ".." in rel_path.split("/"):
            raise ExtractionError(f"unsafe asset path: {rel}")
        decoded = base64.b64decode(binary_assets[rel], validate=True)
        write_bytes(PROJECT_ROOT / "assets" / "binary" / rel_path, decoded)
        binary_meta.append({
            "path": rel,
            "file": f"assets/binary/{rel_path}",
            "sha256_decoded": sha256(decoded),
            "declared_size": files[rel],
            "decoded_size": len(decoded),
            "b64_sha256": sha256(binary_assets[rel].encode("ascii")),
        })

    # ---- generated support files --------------------------------------------
    write_text(PROJECT_ROOT / "src" / "assets" / "init.lua", ASSETS_INIT)
    write_text(PROJECT_ROOT / "src" / "modules" / "example.lua", EXAMPLE_MODULE)
    write_text(
        PROJECT_ROOT / "src" / "modules" / "init.lua",
        MODULES_INIT_HEADER.format(ENTRIES='modules["example"] = require("modules.example");\n\n'),
    )

    # keep a pristine copy of the input inside the project
    project_input = PROJECT_ROOT / "input" / "message(47).txt"
    if not project_input.exists() or project_input.read_bytes() != raw:
        project_input.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(INPUT_FILE, project_input)

    # ---- extraction manifest -------------------------------------------------
    extract_manifest = {
        "generated_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "input": {"path": "input/message(47).txt", "sha256": sha256(raw), "bytes": len(raw)},
        "payloads": {
            name: {
                "sha256": sha256(payloads[name].encode("utf-8")),
                "chars": len(payloads[name]),
                "file": dest,
            }
            for name, dest in (
                ("SOURCE", "src/neverlose/init.lua"),
                ("LIBRARY_SOURCE", "src/visualsui/init.luau"),
                ("BOOT_DATA", "assets/boot_data.json"),
                ("SKIN_SOURCE", "src/neverlose/skins.luau"),
            )
        },
        "driver": {
            "sha256": sha256(payloads["DRIVER"].encode("utf-8")),
            "chars": len(payloads["DRIVER"]),
            "file": "src/init.lua (verbatim tail after the marker line)",
            "marker": MARKER,
        },
        "boot_data": {
            "manifest_count": manifest["count"],
            "manifest_files": len(files),
            "manifest_total": manifest["total"],
            "skyboxes": len(skyboxes),
            "text_assets": text_meta,
            "binary_assets": binary_meta,
        },
    }
    write_text(PROJECT_ROOT / "scripts" / "extract_manifest.json",
               json.dumps(extract_manifest, indent=2, ensure_ascii=False) + "\n")

    print(f"[extract] wrote src/init.lua + 3 payload chunks + assets "
          f"({len(text_assets)} text, {len(binary_assets)} binary)")
    print("[extract] wrote scripts/extract_manifest.json")
    print("[extract] DONE")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ExtractionError as exc:
        print(f"EXTRACTION FAILED: {exc}", file=sys.stderr)
        sys.exit(2)
